### ISSUE TITLE
Outside-in vs Inside-out

### ISSUE THREAD

**Issue by devmsh** [laracamp/session03#4]
TDD has two school, one called Outside-in and the other called Inside-out.

What is the differences between these schools? and when must we use each of them?

**Comment by kabusaid** [comment]
Inside Out TDD (Bottom Up/Chicago School/Classic Approach)
البدء بالتفاصيل حتى الوصول إلى التطبيق كاملا - صخرة صخرة حتى بناء الجبل
هي طريقة تسمح للمطور بالتركيز على شيء واحد فقط ( موديول أو كلاس ) حتى بناء التطبيق كاملا
مفيدة جدا في عمل الفريق بحيث يمكن أن يعمل الفريق بالتوازي

Outside In TDD (Top Down/London School/Mockist Approach)
تكون الصورة الكبيرة للتطبيق واضحة ومعروفة ثم تبدأ مرحلة اكتشاف التفاصيل
في هذه الطريقة يتم بناء التست على السيناريو الذي طلبه المستخدم
تفاعل أجزاء النظام المختلفة مع بعضها تكون معروفة 
بيقولوا أنه هاي الطريقة جيدة لظهور
 API 
محترم

**Comment by anasanwar** [comment]
**When must we use each of them?**
If you’re not sure how your code should look like or how it will interact or communicate with other parts of your system, it’s better to have a small design discussion with the team to identify the best possible design solution and start with the low level component and let it evolve as you write more tests.

But if your design already exists (Layered approach, where the layered components are identified like controllers, services, repositories etc.), you can start with the **Outside-In** approach.

**Comment by mawadameshal** [comment]
outside-in : covers use case level functionality or is intended for acceptance tests.
developers pick use case and drill into low-level unit tests. objective of outside-in  is to obtain high-level design. the outside-in relies on code for abstraction.
The advantages are as follows:
•	Outside-in is an acceptance test or customer oriented
•	System interfaces are not predefined; tests identify the interfaces and protocol of interaction
•	Design evolves from the test
The disadvantages are as follows:
•	Maintainability of tests.
•	If use case  criteria changes, it creates a ripple effect in unit-level codes, which is a single place of failure.
•	Production code lives with mocks and fakes. If forgotten, they live forever.
----------------------------------------------------------------------------------------------------
inside-out
is mostly followed by developers. High-level objects and interaction are designed first, then unit level classes are coded using TDD. And is a stateless development. Pure JUnit tests with mocking fall under this section.
Developers start with a component/class and add tests for the component; as the tests evolve, new components and interaction between these new components come into picture.
 Inside-out is used once the outside-in interfaces are coded. 
The advantages are as follows:
•	Maintainable, clean production code
The disadvantages are as follows:
•	Upfront design is already done.
•	Time to market a feature is slow as compared to outside-in because someone is creating the big upfront design. Unless the layers are created, unit-level tests cannot be started.

REf: https://www.safaribooksonline.com/library/view/test-driven-development-with/9781783283293/ch04s02.html

**Comment by RamiKerenawi** [comment]
Inside-Out (من الداخل للخارج - المدرسة الكلاسيكية):
وهذه الطريقة تبدأ فيها ببناء اﻻختبارات للمكونات أو الكلاسات التي سأنشئها فيما بعد، واحدًا تلو اﻵخر حتى تنتهي من اختبارهم جميعًا بشكل منفرد، ثم اختبارهم مرتبطين معًا، مع اﻷخذ في اﻻعتبار إعادة هيكلة اﻻختبار عند عمل تعديلات على اﻷكواد أو إضافة مكونات جديدة، وهذه الطريقة التي اتبعناها أمس وهي تعتمد على النتيجة النهائية ﻻ على طريقة الوصول State verification

Outside-In (من الخارج للداخل - مدرسة لندن)
أو كما تسمى (الطريقة التنكرية وتستخدم لاختبار مكون أو كلاس موجود ومبرمج مسبقًا، وهي تعتمد على استعمال مكون لينتحل شخصية مكون آخر أو كلاس آخر (Object Injection) فيقوم بتطبيق نفس الوظائف التي يقوم بها الكلاس اﻷصلي ونزوده ببيانات زائفة حتى يعطينا المخرجات المطلوبة ﻹتمام اﻻختبار، وهذه الطريقة تعتمد على أسلوب الوصول للنتيجة Behavior verification

**Comment by hamzahamada** [comment]
- Inside Out (Classic school, bottom-up): TDD allows the developer to focus on one thing at a time. Each entity (i.e. an individual module or single class) is created until the whole application is built up.
Inside out coding is great because you always have something working. The downside is that it doesn’t necessarily help you get to a radically different place. It is harder to chart a course this way. 

- writing code outside in has the downside of not necessarily having the benefit of rapid iterative development, and not necessarily seeing all of the opportunities and patterns that may arise from deep in the structure of the code.

**Comment by mohuml** [comment]
- Inside Out TDD (Bottom Up/Chicago School/Classic Approach):
allows the developer to focus on one thing: individual module or single class also, we can choose this way if we are not sure how the code will be or how it will interact with parts of system.

- Outside In TDD (Top Down/London School/Mockist Approach)"
The tests are based upon user-requested scenarios, and entities are wired together from the beginning. The developer starts building a whole system, and breaks it down into smaller components when **refactoring opportunities arise**

**Comment by Wafaa122** [comment]
inside-Out (Classic school, bottom-up): you begin at component/class level (inside) and add tests to requirements. As the code evolves (due to refactorings), new collaborators, interactions and other components appear. TDD guides the design completely.

Outside-In (London school, top-down or "mockist TDD" as Martin Fowler would call it): you know about the interactions and collaborators upfront (especially those at top levels) and start there (top level), mocking necessary dependencies. With every finished component, you move to the previously mocked collaborators and start with TDD again there, creating actual implementations (which, even though used, were not needed before thanks to abstractions).
